import React, { useEffect, useState } from "react";
import axios from "axios";
import "./ProfitLossReport.css";

// Function to generate the profit and loss report
const ProfitLossReport = () => {
  const [revenuedata, setRevenueData] = useState([]);
  const [expensedata, setExpenseData] = useState([]);
  const [totalRevenueAmount, setTotalRevenueAmount] = useState(0);
  const [totalExpenseAmount, setTotalExpenseAmount] = useState(0);

  const handlePrint = () => {
    // Hide other sections before printing
    document.querySelectorAll(".hide-on-print").forEach((section) => {
      section.style.display = "none";
    });

    // Trigger print
    window.print();

    // Restore display styles after printing
    document.querySelectorAll(".hide-on-print").forEach((section) => {
      section.style.display = "block";
    });
  };

  // For fetching revenue and expense data
  const fetchData = async () => {
    try {
      const [revenueResponse, expenseResponse] = await Promise.all([
        axios.get("http://localhost:8080/api/v1/revenue/viewRevenue"),
        axios.get("http://localhost:8080/api/v1/expense/viewExpense"),
      ]);

      if (revenueResponse.data && revenueResponse.data.content) {
        setRevenueData(revenueResponse.data.content);

        // Calculate total revenue amount
        const totalRevenue = revenueResponse.data.content.reduce(
          (sum, item) => sum + item.amount,
          0
        );
        setTotalRevenueAmount(totalRevenue);
      }

      if (expenseResponse.data && expenseResponse.data.content) {
        setExpenseData(expenseResponse.data.content);

        // Calculate total expense amount
        const totalExpense = expenseResponse.data.content.reduce(
          (sum, item) => sum + item.amount,
          0
        );
        setTotalExpenseAmount(totalExpense);
      }
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div className="report-container">
      <header className="report-header">
        <h1>Profit and Loss Report</h1>
        <h2>Smart Apparel International (PVT) LTD.</h2>
        <h3>Thudawa, Mathara.</h3>
        <p>Date: {new Date().toLocaleDateString()}</p>
      </header>

      <section className="report-section">
        <h2>Overview</h2>
        <p>This section provides an overview of the Revenue and Expenses.</p>
      </section>

      <h2>Financial Summary</h2>

      <section className="printable-section">
        <div className="container">
          <div className="card">
            <div className="card-body">
              <table className="table borderless">
                <thead className="bg-dark text-white">
                  <tr>
                    <th colSpan={3}>
                      <h5>Revenue</h5>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {revenuedata.map((item) => (
                    <tr key={item.revenue_ID}>
                      <td>{item.date}</td>
                      <td>{item.description}</td>
                      <td>{item.amount}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </section>

      <section className="printable-section">
        <div className="container">
          <div className="card">
            <div className="card-body">
              <table className="table borderless">
                <thead className="bg-dark text-white">
                  <tr>
                    <th colSpan={3}>
                      <h5>Expense</h5>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {expensedata.map((item1) => (
                    <tr key={item1.expense_ID}>
                      <td>{item1.date}</td>
                      <td>{item1.description}</td>
                      <td>{item1.amount}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </section>

      <section className="report-section">
        <p style={{ textAlign: "right", fontSize: 25 }}>
          Net Profit: <b>Rs. {totalRevenueAmount - totalExpenseAmount}</b>
        </p>
      </section>

      <section className="report-section">
        <h2>Key Metrics</h2>
        <p>
          The Profit and Loss (P & L) account, also known as the income
          statement, summarizes a company's financial performance over a
          specific period, usually a fiscal year. It presents the revenues
          generated from sales and other sources against the expenses incurred
          to generate those revenues.
        </p>
      </section>

      <footer className="report-footer">
        <p>Generated by Smart Apparel International Reporting System</p>
        <p>Date Generated: {new Date().toLocaleDateString()}</p>
      </footer>

      {/* Print button */}
      <button
        className="print-button hide-on-print"
        id="printBtn"
        onClick={handlePrint}
      >
        Print Report
      </button>
    </div>
  );
};

export default ProfitLossReport;
