import { useEffect, useState } from "react";
import axios from "axios";
import './ProfitLossReport.css'; // Import CSS for styling
import Box from "@mui/material/Box";
import { Padding } from "@mui/icons-material";


const ReportStructure = () => {

  const [revenuedata, setRevenueData] = useState([]);
  const [expensedata, setExpenseData] = useState([]);
  const [totalRevenueAmount, setTotalRevenueAmount] = useState(0);
  const [totalExpenseAmount, setTotalExpenseAmount] = useState(0);

  const handlePrint = () => {
    window.print();
  };

  useEffect(() => {
    axios
      .get("http://localhost:8080/api/v1/revenue/viewRevenue")
      .then((response) => {
        if (response.data && response.data.content) {
          setRevenueData(response.data.content);

          // Calculate total revenue amount
          const totalRevenue = response.data.content.reduce(
            (sum, item) => sum + item.amount,
            0
          );
          setTotalRevenueAmount(totalRevenue);
        }
      })
      .catch((error) => {
        console.error("Error fetching revenue data:", error);
      });

    axios
      .get("http://localhost:8080/api/v1/expense/viewExpense")
      .then((response) => {
        if (response.data && response.data.content) {
          setExpenseData(response.data.content);

          // Calculate total expense amount
          const totalExpense = response.data.content.reduce(
            (sum, item) => sum + item.amount,
            0
          );
          setTotalExpenseAmount(totalExpense);
        }
      })
      .catch((error) => {
        console.error("Error fetching expense data:", error);
      });
  }, []);

  return (
    <div className="report-container">
      <header className="report-header">
        <h1>Profit and Loss Report</h1>
        <h2>Smart Apparel International (PVT) LTD.</h2>
        <h3>Thudawa, Mathara. </h3>
        <p>Date: {new Date().toLocaleDateString()}</p>
      </header>

      <section className="report-section">
        <h2>Overview</h2>
        <p>This section provides an overview of the Revenue and Expenses.</p>
      </section>

      <h2>Financial Summary</h2>
      

      <Box sx={{ display: "flex" }}>
        <div className="container">
          <div className="card">
            <Box height={30} />
            <div className="card-body">
              <table className="table borderless">
                <thead className="bg-dark text-white">
                  <tr>
                    <th colSpan={3}><h5>Revenue</h5></th>
                  </tr>
                </thead>
                <tbody>
                  {revenuedata.map((item) => (
                    <tr key={item.revenue_ID}>
                      <td>{item.date}</td>
                      <td>{item.description}</td>
                      <td>{item.amount}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </Box>

      <Box sx={{ display: "flex" }}>
        <div className="container">
          <div className="card">
            <Box height={30} />
            <div className="card-body">
              <table className="table borderless">
                <thead className="bg-dark text-white">
                  <tr>
                    <th colSpan={3}><h5>Expense</h5></th>    
                  </tr>
                </thead>
                <tbody>
                  {expensedata.map((item1) => (
                    <tr key={item1.expense_ID}>
                      <td>{item1.date}</td>
                      <td>{item1.description}</td>
                      <td>{item1.amount}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </Box>

      <Box height={30} />
      <section className="report-section" sx={{Padding:50}}>
        <p style={{ textAlign: "right",fontSize: 25}}>Net Profit: <b>Rs.{totalRevenueAmount - totalExpenseAmount}</b></p>
      </section>
     
      <Box height={30} />
      <section className="report-section">
        <h2>Key Metrics</h2>
        <p>The Profit and Loss (P & L) account, also known as the income statement, summarizes a company's financial performance over a specific period, usually a fiscal year. It presents the revenues generated from sales and other sources against the expenses incurred to generate those revenues.</p>
      </section>

      <footer className="report-footer">
        <p>Generated by Smart Apparel International Reporting System</p>
        <p>Date Generated: {new Date().toLocaleDateString()}</p>
      </footer>

      {/* Print button */}
      <button className="print-button" id="printBtn" onClick={handlePrint}>
        Print Report
      </button>
    </div>
  );
};

export default ReportStructure;
